src_dir: "data/traps/1"
mapping: "model/class_map_animal.txt"
device: cuda
dst_save_table: "data/table.csv"

logger:
  log_dir: "logs"
  log_file: "log.txt"

detector:
  weights: "model/weights/detection/yolov8n.pt"
  batch_size: 1
  iou: 0.45
  conf: 0.4
  imgsz:
    - 640
    - 640

classificator:
  weights: "model/weights/classification/efficientnet_b0.pt"
  batch_size: 8
  imgsz:
    - 288
    - 288